# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
on: [push, pull_request]
# Controls when the action will run. By default, this action runs on every push and pull request.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      run: go build -v -o OpenBloxLoader-Debug-Nightly.exe  ./... 
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: OpenBloxLoader (Debug) (${{ github.sha }})
        path: .\OpenBloxLoader-Debug-Nightly.exe
