# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Get Fyne
      run: go get fyne.io/fyne/v2@latest

    - name: Install Fyne
      run: go install fyne.io/fyne/v2/cmd/fyne@latest

    - name: Build
      run: fyne build -o OpenBloxLoader-Debug-Nightly.exe
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: OpenBloxLoader (Debug) (${{ github.sha }})
        path: .\OpenBloxLoader-Debug-Nightly.exe